apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 192.168.112.101
clientConnection:
  kubeconfig: /etc/kubernetes/kube-proxy.kubeconfig
clusterCIDR: 172.30.0.0/16
healthzBindAddress: 192.168.112.101:10256
hostnameOverride: node01
kind: KubeProxyConfiguration
metricsBindAddress: 192.168.112.101:10249
mode: "ipvs"
